# =============================================================================
# importing external packages
import numpy as np
from sympy import symbols, Eq, simplify, Function, Add, solve
#from libcellml import Parser, Printer, Validator, cellmlElementTypeAsString
from colorama import Fore, Back, Style, init
import os
import sys



# Importing internal packages
from utilities import print_model
import compound_element_sorter as ces
import equations_from_text as eft
import chebi_fetch as chf


def kietic_thermo_convertor( components, reaction_indices, compound_indices, coefficients, printing = 'off' ):

    '''
    This function gets the components of the CellML file and finds forward and reverse reaction rate constants
    '''

    # ------------ << Calling sorter function to sort the variables into their corresponding lists >> --------------
    variables, _ , _ , reaction_rates, reaction_rate_constants, boundary_conditions, equation_variables, boundary_values = ces.variable_sorter( components )

    # variables => This list contains the concentration variables of compounds in cellml file [In CellML file]
    # coefficients => The difference between variables and coefficients is identified by the first part of their id which is like "va_12345_r1", first part indicates that this parameter is a variable
    # enzymes => This list contains the enzymes participating in reactions. Enzymes participate in reaction but not included in stoichiometric matrix so they should be treated differently.
    # reaction_rates => This list contains all the rate variables (classes) for all equations that are in the model
    # reaction_rate_constants => This list contains the rate constants (classes) that are in the model
    # boundary_conditions => This list stores the boundary condition variables (classes) defined by the user

    # Initialize colorama
    init(autoreset=True)

    # --------------- << Since we build the equations from the coefficients and reaction rates given in the CellML file, if there are no reaction rates, we cannot build the equations >> --------------------
    if not reaction_rates:

        command = 'cls' if os.name == 'nt' else 'clear'
        os.system(command)
    
        print( Style.BRIGHT + Fore.RED + "Since there are no reaction rates defined separately for the CellML file, the equations cannot be generated by this Python code at this moment\n\n" )
        exit()

    reaction_rates_constants = {}

    for reaction_rate_constant in reaction_rate_constants:

        reaction_id = reaction_rate_constant.id()

        reaction_name = reaction_id.split('_')[2]

        direction = reaction_id.split('_')[1]

        if reaction_name not in reaction_rates_constants:

            reaction_rates_constants[reaction_name] = {}

        if direction == 'f':

            reaction_rates_constants[reaction_name]["forward"] = float( reaction_rate_constant.initialValue() )

        elif direction == 'r':

            reaction_rates_constants[reaction_name]["reverse"]= float( reaction_rate_constant.initialValue() )

    
    reactions_no = len( reaction_indices )

    identity_array = np.eye( reactions_no )

    vector_length = reactions_no * 2

    kinetic_constants = np.zeros( vector_length )

    for reaction_name, reaction_index in reaction_indices.items():

        try:
        
            k_plus = reaction_rates_constants[reaction_name]["forward"]

            kinetic_constants[reaction_index] = k_plus

        except:

            sys.exit( "The forward reaction rate constant was not found {r}".format( r = reaction_name ) )

        try:

            k_minus = reaction_rates_constants[reaction_name]["reverse"]

            kinetic_constants[ (reaction_index + reactions_no ) ] = k_minus

        except:

            sys.exit( "The reverse reaction rate constant was not found for reaction {r}".format( r = reaction_name ) )





        
    




    # In this part, forward and reverse Stoichiometric matrices will be built

    columns = len( reaction_indices )                                               # Number of columns will be equal to number of reactions in the Stoichiometric matrix

    rows = len( compound_indices )                                                  # Number of rows will be equal to number of compounds in the Stoichiometric matrix

    forward_stoichiometric_matrix = np.zeros(( rows, columns), dtype = int)                 # A numpy matrix is made to construct the forward stoichiometric matrix

    reverse_stoichiometric_matrix = np.zeros(( rows, columns), dtype = int)                 # A numpy matrix is made to construct the reverse stoichiometric matrix

    # to construct the stoichiometric matrix, we need to go through all coeffcients for all compounds
    for coefficient in coefficients:

        chebi_code = coefficient.id().split('_')[1]                                 # At first we get the compound chebi code which this coeffcient belongs to

        reaction_parts = coefficient.id().split('_')[2].split('-')                            # Then we get the reaction which this coeffcient is applied for this compound
        
        already_added = []

        for reaction_part in reaction_parts:

            reaction_number = reaction_part.split('.')[0]

            if reaction_number in already_added:

                continue
            
            already_added.append( reaction_number )

            # We construct the stoichiometric matrix based on the chemical formulas of the compounds not the variable name that the user has given to it
            if ces.all_digits( chebi_code ):

                formula = chf.chebi_formula( chebi_code )                               # If the chebi code part is all digits, it is considered as chebi code, otherwise it is the name of the compound

            else:

                formula = chebi_code

            # Now we will try getting the row index for this compound. We have stored indices for the compounds as we were reading all of them from the CellML file
            try:

                row = compound_indices[formula]

            except KeyError as KE:

                print("TThere is not a variable for compound {v} in CellMl while there is a stoichiometric coefficient defined for it.".format( v = KE ))
                sys.exit("Exiting due to an error\nModify CellML file and check to see if you have this compound or errors in a ChEBI code in reaction {r}".format( r = reaction_number ))


            column = reaction_indices[ reaction_number ]                                  # Now we try to get the column for this compound which is the reaction in which this compound participates with this coefficient

            value = int( coefficient.initialValue() )

            if value < 0:

                forward_stoichiometric_matrix[ row, column ] = abs( value )           # Then we store the value of the coefficient in the stoichiometric matrix

            elif value > 0:

                reverse_stoichiometric_matrix[ row, column ] = abs( value )          # Then we store the value of the coefficient in the stoichiometric matrix

    transposed_forward_stoichiometric_matrix = np.transpose( forward_stoichiometric_matrix )

    transposed_reverse_stoichiometric_matrix = np.transpose( reverse_stoichiometric_matrix )

    conversion_matrix = np.block( [ [ identity_array, transposed_forward_stoichiometric_matrix ], [ identity_array, transposed_reverse_stoichiometric_matrix ] ] )

    return conversion_matrix, kinetic_constants