# =============================================================================
# importing external packages
from sympy import symbols, Eq, simplify, Function, Add, solve
#from libcellml import Parser, Printer, Validator, cellmlElementTypeAsString
from colorama import Fore, Back, Style, init
import os
import sys


# Importing internal packages
from utilities import print_model
import compound_element_sorter as ces
import equations_from_text as eft


def reversibility_check( components,  printing = 'off' ):

    '''
    This function gets the components of the CellML file and finds forward and reverse reaction rate constants
    '''

    # ------------ << Calling sorter function to sort the variables into their corresponding lists >> --------------
    variables, _ , _ , reaction_rates, reaction_rate_constants, boundary_conditions, equation_variables, boundary_values = ces.variable_sorter( components )

    # variables => This list contains the concentration variables of compounds in cellml file [In CellML file]
    # coefficients => The difference between variables and coefficients is identified by the first part of their id which is like "va_12345_r1", first part indicates that this parameter is a variable
    # enzymes => This list contains the enzymes participating in reactions. Enzymes participate in reaction but not included in stoichiometric matrix so they should be treated differently.
    # reaction_rates => This list contains all the rate variables (classes) for all equations that are in the model
    # reaction_rate_constants => This list contains the rate constants (classes) that are in the model
    # boundary_conditions => This list stores the boundary condition variables (classes) defined by the user

    # Initialize colorama
    init(autoreset=True)

    # --------------- << Since we build the equations from the coefficients and reaction rates given in the CellML file, if there are no reaction rates, we cannot build the equations >> --------------------
    if not reaction_rates:

        command = 'cls' if os.name == 'nt' else 'clear'
        os.system(command)
    
        print( Style.BRIGHT + Fore.RED + "Since there are no reaction rates defined separately for the CellML file, the equations cannot be generated by this Python code at this moment\n\n" )
        exit()


    for reaction_rate in reaction_rates:

        reaction_id = reaction_rate.id()

        reaction_no = reaction_id.split('_')[1]

        matched_consts = []

        for reaction_rate_const in reaction_rate_constants:

            reaction_const_id = reaction_rate_const.id()

            reaction_const_no = reaction_const_id.split('_')[2]

            if reaction_const_no == reaction_no:

                matched_consts.append(reaction_rate_const)

        forward_rate = False

        reverse_rate = False

        for reaction_rate_const in matched_consts:

            reaction_const_id = reaction_rate_const.id()

            direction = reaction_const_id.split('_')[1]

            if direction == 'f':

                forward_rate = True
                
            elif direction == 'r':

                reverse_rate = True

        infeasible = False

        if not forward_rate or not reverse_rate:

            infeasible = True

            print( "\nReaction" + Style.BRIGHT + Fore.BLUE + " {r} ".format( r = reaction_no ) + Style.NORMAL + Fore.WHITE + "is not reversible and" + Style.BRIGHT + Fore.RED + " violates Thermodynamic feasibility principle" + Style.NORMAL + Fore.WHITE +  " for biochemical reactions")

        # if infeasible:

        #     sys.exit( Fore.YELLOW + "\nThe model is not Thermodynamcally feasible since the reactions are not reversible\n\n")